### ISSUE TITLE
Error with https://qubyte.codes/notes/1572217565280

### ISSUE THREAD

**Issue by qubyte** [remy/wm#12]
URL: https://qubyte.codes/notes/1572217565280
Status: 200
Error: `No webmention endpoints found in the 1 content entry`

Please note, the content at this URL will change. At the time of writing the relevant content looked like:

```html
<article class="h-entry">
  <header>
    <a class="u-url" href="/notes/1572217565280"><time datetime="2019-10-27T23:06:05.280Z" class="dt-published">Sun, 27 Oct 2019 23:06:05 GMT</time></a>
  </header>
  <p class="p-content p-name">Testing out syndication of a note from my blog.</p>
  <a href="https://brid.gy/publish/twitter"></a>
  <a href="https://brid.gy/publish/mastodon"></a>
</article>
```

The two anchors at the bottom _should_ trigger webmention behaviour. If I curl either I get back a minimal page intended to trigger webmention dispatchers:

```html
<!DOCTYPE html>
<html><head>
<link rel="webmention" href="https://brid.gy/publish/webmention">
</head>
<body>Nothing here! <a href="/about">Try the docs instead.</a></body>
```

However, they don't and I'm having trouble figuring out why.

**Comment by qubyte** [comment]
Darn. Sorry, this seems to be some unrelated issue but I need to reduce it first. Other links without microformats markup are dispatching fine, but not those in the snippet above (could be to do with no text in the anchors or something, but I'm guessing...)

**Comment by qubyte** [comment]
Updated the description to suit the problem (possibly isolated to brid.gy anchors for some reason).

**Comment by qubyte** [comment]
The problem was two-fold:
 - When an h-entry is on the page, this module ignores anchors which aren't children of it.
 - I used a `p-content` when I should have used an `e-content`.

**Comment by hirusi** [comment]
Hi @qubyte, I also see that the current `e-content` on your page is:

```
      <p class="e-content p-name">
        Testing out syndication of a note from my blog.
        <a class="mention-of" href="https://brid.gy/publish/twitter"></a>
        <a class="mention-of" href="https://brid.gy/publish/mastodon"></a>
      </p>
```

Was it adding the `mention-of` class that finally got it working, in addition to the two points you mentioned in https://github.com/remy/wm/issues/12#issuecomment-546754231? Could you please explain a bit more, if possible, why `mention-of` works and is required?

**Comment by qubyte** [comment]
It's been a while, so I don't remember clearly. I _think_ it may be because when wm sees a page with some microformats markup, it assumes each link out will be marked up as a `mention-of`. There's the end of that thread to pull on: https://github.com/remy/wm/blob/86d8f12f3d701a330ffedabebee873cbb1a52167/lib/webmention.js#L109-L113

**Comment by hirusi** [comment]
I see, thanks for your prompt response.

In the case of microformats, it looks like wm only collects links if they have any of the following classes in the `types` array. This is why the brid.gy links must be getting ignored by themselves.

https://github.com/remy/wm/blob/a60358ba163607a84a69960726d35f4cbeb4e135/lib/microformat/dom.js#L63-L98

@remy Could I interest you in a quick explanation by any chance? Is what I deduced above correct?

**Comment by hirusi** [comment]
Further testing locally using the `@remy/webmention` command line utility reveals the following:

When tested with a permalink of a note, where `wm` detects it as a `microformat`:

1. The link *must* be a child of the tag carrying the `e-content` class. Being a child of `h-entry` does not suffice.
2. The link *does not* need to carry any of the class names mentioned above in my earlier comment.

When tested with an atom feed, where `wm` detects it as an `RSS feed`:

1. A link being present in in the tree structure as follows: `<feed><entry><content type="html><a href="https://brid.gy/publish/mastodon"></a></content></entry></feed>` whether carrying a wm-property (`like-of`, `mention-of` etc.) class or not, has no effect in how `wm` parses it.

**Comment by remy** [comment]
Picking these up on a Sunday bleery eyed, but wanted to resolve these issues (only 6 months late, eh!).

@qubyte when I test webmention.app against that URL it picks up the two links - I suspect this was fixed somewhere along the line and I didn't think to close this issue.

@hirusi I'm going to test your case separately but close this issue - I'm still not 100% sure which `type` web mentions prefer, but I'll create a test and code against that.

Let me know if closing this is wrong - ta!
