### ISSUE TITLE
Error on check

### ISSUE THREAD

**Issue by aaronpk** [remy/wm#2]
```
URL: https://aaronparecki.com/2019/05/22/10/indieweb-summit
Status: 200
Error: `No webmentions found on 1 discovered entries`
```

* I really like this shortcut to create an issue! I might have to steal this idea!
* The text should probably say "no webmention endpoints found" since people usually say "webmentions" when they're referring to receiving comments via webmention
* this should have found the webmention endpoint for https://2019.indieweb.org/summit

**Comment by remy** [comment]
1. Do! :)
2. Ta - will update
3. Hmm, that _should_ work - initial checks show that the source is good, but you're right, my code isn't spotting it. I'll dig in tonight and get back to you 👍

**Comment by remy** [comment]
1.3.6 CLI tool has fix and online fix is being deployed right now.
