### ISSUE TITLE
Trying to do webmention.rocks tests... having problems.

### ISSUE THREAD

**Issue by jasikpark** [remy/wm#36]
I'm trying to set up webmentions for my site and following https://webmention.rocks/update/1

I used the webmentions modal at the bottom of https://webmention.app/ to try testing it out but when I got to the second step I got an error: 
<img width="625" alt="Screen Shot 2021-01-16 at 1 51 08 PM" src="https://user-images.githubusercontent.com/10626596/104821499-ea0f1280-5801-11eb-8b00-478636ad3855.png">

Are these responses to the webmentions sent to each url?

**Comment by remy** [comment]
These are errors from webmention.rocks - and I'm guessing they're legitimate.
