### ISSUE TITLE
Resending webmention every time

### ISSUE THREAD

**Issue by devilgate** [remy/wm#38]
Hi, I'm just trying this out. Seems that it's sending the same webmention every time it runs, even when the RSS feed hasn't changed. Is there a way to make it aware of the items it has processed?

**Comment by remy** [comment]
No, both the web interface and the command line tool are stateless, so you'll need something *outside* of execution to test for changes. 

At the same time though, the recieving end of the webmention *will* handle repeat sends from the same source (or at least it's up to the implementation on the recieving side to handle this), so technically you're safe to keep resending.
