### ISSUE TITLE
Error with https://kiko.io/post/Mastodon-simply-explained/

### ISSUE THREAD

**Issue by kristofzerbe** [remy/wm#52]
URL: https://kiko.io/post/Mastodon-simply-explained/
Status: 200
Error: `No webmention endpoints found in the 1 content entry`

Don't know what's going on, but I received Webmentions for this URL in the past. Just tried test page of webmention.app for new area URL's and got always 'no webmention endpoints found...', even for this 'old' URL, which had worked in the past...!?

**Comment by aciccarello** [comment]
I think the confusion (at least for myself) is that none of the linked sites support webmentions. Webmention.app is about outgoing webmentions rather than incoming webmentions.

I think the error would be easier to understand if it said

> Error: No webmention endpoints found in **the links of** the 1 content entry

**Comment by remy** [comment]
@aciccarello I've added that text change and will push to help clarify. Am going to close this issue @kristofzerbe (appreciate it's 3 months old!) but once webmentions.app is back up, it'll include this fix (and I'll push the command line tool sooner too).
