### ISSUE TITLE
Error with https://blog.behaghel.org/posts/2022/12/hello-world/

### ISSUE THREAD

**Issue by behaghel** [remy/wm#53]
URL: https://blog.behaghel.org/posts/2022/12/hello-world/
Status: 200
Error: `No webmention endpoints found in the 1 content entry`

https://indiewebify.me/send-webmentions/ finds 2 webmentions with the same URL.

**Comment by aciccarello** [comment]
I'm not sure what URLs indiewebify.me sent webmentions to but I did submit it again and it still found 2. I see at least one self-referential URL which webmention.app currently does not support (#30). That's the only one https://telegraph.p3k.io finds.

<img width="713" alt="Screenshot of Telegraph webmention tool listing 4 URLs without webmention endpoints and listing the about page as supporting webmentions" src="https://user-images.githubusercontent.com/11273838/221330521-5aef38ca-ea64-472d-9e46-59732a4eabd5.png">

**Comment by behaghel** [comment]
Thanks @aciccarello! I am not sure anymore why I thought it should behave differently. It was 2022. I was tired that year. Closing!
