### ISSUE TITLE
Error with https://mastodon.technology/users/da.atom

### ISSUE THREAD

**Issue by da2x** [remy/wm#6]
URL: https://mastodon.technology/users/da.atom
Status: 200
Error: `No webmention endpoints found in the 10 content entries`

Mastadon generated Atom feeds don't seem to work. Replace .atom with .rss and it works, suggesting there is an issue with the Atom feed parser.

**Comment by remy** [comment]
Acknowledged. I'm on holiday at the moment, but I'll take a look at the fix
once I'm back 👍

I suspect the parser I'm using isn't doing the parse job properly.

**Comment by remy** [comment]
Long time to reply, but I'm seeing something odd here, the RSS and the ATOM feed actually contain different items.

For instance, there's a link to https://www.ctrl.blog/entry/coil-web-monetization.html in the RSS feed but it doesn't appear in the ATOM feed. 

Is this actually a problem with the generated feeds rather than the WebMention script?

**Comment by da2x** [comment]
I can no longer reproduce the issue. I should have attached a copy of the feed as it appeared in July. You’d just launched the service so I assumed you’d look into it right away. I didn't think to save a copy of the original feed. (It passed feed validation at the time.)

It’s a difference in how Mastadon does feeds. The Atom feed contains user posts *and* replies while the RSS feed only contains user posts.

**Comment by remy** [comment]
I did originally but in the end "real" work took up my time.

If you see this again, please don't hesitate to raise an issue again. I've also closed a couple of atom related bugs in the mean time so it's possible that it's been fixed through those too.

**Comment by remy** [comment]
I'll close for now if that's cool.
