### ISSUE TITLE
Error with https://feed.ctrl.blog/latest.atom

### ISSUE THREAD

**Issue by da2x** [remy/wm#7]
URL: https://feed.ctrl.blog/latest.atom
Status: 200
Error: `Cannot read property '0' of null`

The feed passes W3C's feed validator and links to pages with links to Webmentionable pages.

This is my feed so let me know if you've got any questions about it.

**Comment by remy** [comment]
Hi there, a bit late, but I've been picking up bugs on this repo - and I'm getting a very strange response: https://webmention.app/test?url=https://feed.ctrl.blog/latest.atom

> Unmatched selector: (UFW). UFW is the default firewall in Ubuntu and has more intuitive commands that require less typing. Both UFW and FirwallD are front-ends for the Linux kernel’s ip…

**Comment by da2x** [comment]
It doesn't like strings with parentheses? [The feed is perfectly valid XML and Atom](https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Ffeed.ctrl.blog%2Flatest.atom), so this seems to be on your side.

**Comment by remy** [comment]
I've fixed and published this. It was borking trying to get the summary text, but I also upgraded to get the HTML content from your feed first if it exists.
